
exp_path: logs/test_baseline_500_50k
img_dataset_path: ../data/unity_images_500
test_dataset_path: ../data/unity_images_test
baseline: True

### INGP
total_training_steps: 50000


### Unity 
object_family: 02843684 
object_id: 1b73f96cf598ef492cba66dc6aeabcd4
pose_max: 8   # Range limit for positions.
pose_min: 3
total_images: 500

# ### RL
# iteration_time: 10   # n_steps and total_images will be divided by this
# episodes: 100