
exp_path: logs/test_500_35k
img_dataset_path: ../data/unity_images_500
test_dataset_path: ../data/unity_images_test
baseline: False

### INGP
total_training_steps: 35000


### Unity 
object_family: 02843684 
object_id: 1b73f96cf598ef492cba66dc6aeabcd4
pose_max: 8   # Range limit for positions.
pose_min: 3
total_images: 500

### RL
K: 20   # n_steps and total_images will be divided by this
episodes: 100


